apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ourbox-apps
  namespace: ourbox-system
spec:
  rules:
    - host: files.ourbox-matchbox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dufs
                port:
                  number: 5000
    - host: notes.ourbox-matchbox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flatnotes
                port:
                  number: 8080
    - host: todo.ourbox-matchbox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-bloom
                port:
                  number: 80
  defaultBackend:
    service:
      name: landing
      port:
        number: 80
