apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: landing
  namespace: ourbox-system
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: landing
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dufs
  namespace: ourbox-system
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`files.{domain:.+}`)
      kind: Rule
      priority: 100
      services:
        - name: dufs
          port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flatnotes
  namespace: ourbox-system
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`notes.{domain:.+}`)
      kind: Rule
      priority: 100
      services:
        - name: flatnotes
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: todo-bloom
  namespace: ourbox-system
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`todo.{domain:.+}`)
      kind: Rule
      priority: 100
      services:
        - name: todo-bloom
          port: 80
